### ISSUE TITLE
Bovitz Guest Survey Sweepstakes Rules Landing Page (BCOP-30)

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/Basic-copy-only-Pages#30]
**New Disclaimer Landing Page for Bovtiz Survey**

**Requestor:** Jessica Beam

**[Workfront Request](https://c21.my.workfront.com/document/view?ID=5a149dc700e651d193badf43ef993de8)**

- [x] Copy Review
- [x] Requestor Review

**Going Live on: 11.30.17**

Final Doc: 
[CENTURY 21 GUEST SURVEY SWEEPSTAKES Legal (1) (2).docx](https://github.com/Century21Stores/BCOP/files/1532816/CENTURY.21.GUEST.SURVEY.SWEEPSTAKES.Legal.1.2.docx)

**Comment by juanmriosv** [comment]
Page completed:
https://www.c21stores.com/pages/bovtiz-survey-disclaimer

**Comment by juanmriosv** [comment]
@AdenaG 
Ready for QA

**Comment by AdenaG** [comment]
@juanmriosv 
validation complete, all looks good. - Daysi
